basePath: /
definitions:
  users.User:
    properties:
      name:
        type: string
    type: object
host: /
info:
  contact:
    email: support@docs.io
    name: API Support
    url: http://www.swagger.io/support
  description: API de users MELI
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: Get Users
      operationId: get-users
      parameters:
      - description: Name
        in: query
        name: name
        required: true
        type: string
      - description: Status
        in: query
        name: status
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.User'
      summary: Get Users without penis
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Get a specific user
      operationId: get-user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.User'
      summary: Get a specific user
swagger: "2.0"
